//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tren_3
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int OrderId { get; set; }
        public string StructureOrder { get; set; }
        public System.DateTime DateOrder { get; set; }
        public System.DateTime DateDelivery { get; set; }
        public int PointOfDelivery { get; set; }
        public string NameUser { get; set; }
        public Nullable<int> VerificationCod { get; set; }
        public string StatusOrder { get; set; }
    
        public virtual PointDelivery PointDelivery { get; set; }
    }
}
